### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by Lcarrico** [fbqvyjt/Game-Dev-Study#2]
Overview links for the _Before we get started_ and _Chapter 1_ are **BROKEN** in the [readme](https://github.com/fbqvyjt/Game-Dev-Study/blob/main/readme.md).

**Comment by Lcarrico** [comment]
@fbqvyjt

**Comment by Lcarrico** [comment]
None of the links for Chapter one works because of the folder rename.
Day-1 → Day-1-Week-1

**Comment by fbqvyjt** [comment]
All Fixed!!! thanks for the help!
